name: .NET

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]
env:
  ROOT: ./src/
  PROJECT: dotnet-spawn
  CONFIGURATION: Release
  VERSION: 0.1
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore ${ROOT}
    - name: Build
      run: dotnet build --configuration ${CONFIGURATION} --no-restore ${ROOT}
    - name: Pack
      run: dotnet pack --configuration ${CONFIGURATION} --no-build ${ROOT} -p:NuspecFile=${ROOT}${PROJECT}/${PROJECT}.nuspec -p:PackageVersion=${VERSION}.${{ github.run_id }}
    - name: Publish
      run: dotnet nuget push --source ${ROOT}${PROJECT}/bin/${CONFIGURATION}/${PROJECT}.${VERSION}.${{ github.run_id }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
